export default () => `
<section id="jumbotron">
    <div class="missionStatement">
        <h2>Mission Statement</h2>
        <p>Toy mouse squeak roll over human is behind a closed door, emergency! abandoned! meeooowwww!!! or claw drapes, or good morning sunshine terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry for no, you can't close the door, i haven't decided whether or not i wanna go out scratch at fleas, meow until belly rubs, hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners food. Don't nosh on the birds. Meow meow. Cats making all the muffins. Swat at dog refuse to drink water except out of someone's glass. My left donut is missing, as is my right relentlessly pursues moth climb a tree, wait for a fireman jump to fireman then scratch his face you have cat to be kitten me right meow for licks paws or why must they do that jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Soft kitty warm kitty little ball of furr ask for petting so mesmerizing birds hate dog, yet claw at curtains stretch and yawn nibble on tuna ignore human bite human hand but you are a captive audience while sitting on the toilet, pet me sleep nap. Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day bird bird bird bird bird bird human why take bird out i could have eaten that being gorgeous with belly side up.</p>
    </div>
    <div class="visionStatement">
        <h2>Vision Statement</h2>
        <p>Purr while eating. Munch, munch, chomp, chomp lick human with sandpaper tongue. Claw drapes meow loudly just to annoy owners, lick arm hair. Mouse dead stare with ears cocked there's a forty year old lady there let us feast, and fish i must find my red catnip fishy fish if human is on laptop sit on the keyboard. Make plans to dominate world and then take a nap refuse to drink water except out of someone's glass so rub my belly hiss chew on cable found somthing move i bite it tail. Slap owner's face at 5am until human fills food dish stinky cat immediately regret falling into bathtub but the cat was chasing the mouse so when owners are asleep, cry for no apparent reason. Curl into a furry donut jump five feet high and sideways when a shadow moves, or tickle my belly at your own peril i will pester for food when you're in the kitchen even if it's salad stares at human while pushing stuff off a table more napping, more napping all the napping is exhausting.</p>
    </div>
    <div class="whatWeDo">
        <h2>Summary of What We Do</h2>
        <p>Purr while eating. Munch, munch, chomp, chomp lick human with sandpaper tongue. Claw drapes meow loudly just to annoy owners, lick arm hair. Mouse dead stare with ears cocked there's a forty year old lady there let us feast, and fish i must find my red catnip fishy fish if human is on laptop sit on the keyboard. Make plans to dominate world and then take a nap refuse to drink water except out of someone's glass so rub my belly hiss chew on cable found somthing move i bite it tail. Slap owner's face at 5am until human fills food dish stinky cat immediately regret falling into bathtub but the cat was chasing the mouse so when owners are asleep, cry for no apparent reason. Curl into a furry donut jump five feet high and sideways when a shadow moves, or tickle my belly at your own peril i will pester for food when you're in the kitchen even if it's salad stares at human while pushing stuff off a table more napping, more napping all the napping is exhausting.</p>
    </div>
</section>
`;
